### ISSUE TITLE
open an associated blogpost in other languages

### ISSUE THREAD

**Issue by muescha** [diogorodrigues/iceberg-gatsby-multilang#6]
maybe it is somehow possible to open the associated pages in the other languages?

if the filename is same then it maybe is easy but when the filenames are different then it should be somehow mapped?

maybe with a filename language mapping json between the translations?

**Comment by diogorodrigues** [comment]
Hi @muescha ! Sorry for the late response.

There is a file to control the menu for each language. See here: https://github.com/diogorodrigues/iceberg-gatsby-multilang/tree/master/config/menu

Are you talking about that?

Thanks

**Comment by muescha** [comment]
## what i do

- if i am on page:
 https://iceberg-gatsby-multilang.netlify.com/blog/creating-posts-and-pages
- i click on pt-BR

## what i expected

- it should open the associated page:
https://iceberg-gatsby-multilang.netlify.com/pt/blog/criacao-de-posts-e-paginas

## what i see instead

- it opens the main page:
https://iceberg-gatsby-multilang.netlify.com/pt

**Comment by webmaeistro** [comment]
@muescha I see what you mean - did you find a workaround?

**Comment by muescha** [comment]
no i not have a workaround :(

**Comment by diogorodrigues** [comment]
I got your idea @muescha . 
I'll think how to handle it. 
Thank you.

**Comment by diogorodrigues** [comment]
@muescha **I implemented what you suggested in the branch `language-mapping`.** Thank you for the suggestions.

**It is now possible to map pages by languages using a JSON file:** https://github.com/diogorodrigues/iceberg-gatsby-multilang/blob/language-mapping/config/language-mapping/index.json

I will still need to improve the business logic of this implementation to ensure that it becomes more dynamic. You can check here: https://github.com/diogorodrigues/iceberg-gatsby-multilang/blob/language-mapping/src/components/Languages/index.js

@webmaeistro could you also check and give me the feedback, please?

**Comment by diogorodrigues** [comment]
Now this functionality is in master branch! ✌✔
